### PR TITLE
Replace static routes with dynamic

### PR DESCRIPTION
**Pull request by chtzv**
#47 Use lazy loading of routes

**Description** :    
Replaced static routes with dynamic

### CODE REVIEW

**Comment by francoiscrouzet** [comment]
@chtzv (@AlZorba)

Ok interressant !!! Thanks !

Below is what I measured with `npm run build`, so it seems that in gzip, we stay in both case at 95kb, so no overhead of cutting the js in several chunk,  but we do have gain of speed loading of each page, and of course if the person goes only to one route. Not sure I am right, but that's the way I understand it. What do you think ?

I don't see the things loading lazily in dev, I guess it only works for the production build

I am not sure the 404 should be lazy loaded, but I don't think it hurt either, no ?

A bit confused that `utils.js` is in its separate file

It could be interressant to measure the web vitals before and after, but I have no time for the moment, maybe later. (and should be in production mode too)

This whole thing, if I remember well, is also dependant of http2 or not, which can make parallel laoding. Not sure, need to re-read about it

Before
```
vite v4.2.1 building for production...
✓ 183 modules transformed.
dist/index.html                    1.89 kB
dist/assets/ThaCER-644de002.svg   17.35 kB
dist/assets/index-012c1725.css     2.02 kB │ gzip:  0.78 kB
dist/assets/index-e58e3d26.js    284.03 kB │ gzip: 94.60 kB │ map: 1,655.58 kB
✓ built in 2.01s
```

After:
```
vite v4.2.1 building for production...
✓ 184 modules transformed.
dist/index.html                        1.89 kB
dist/assets/ThaCER-644de002.svg       17.35 kB
dist/assets/index-37355842.css         0.15 kB │ gzip:  0.13 kB
dist/assets/TheMap-9aacb573.css        1.87 kB │ gzip:  0.73 kB
dist/assets/utils-c62df14f.js          0.12 kB │ gzip:  0.13 kB │ map:     0.32 kB
dist/assets/NotFound404-923e1f4e.js    0.44 kB │ gzip:  0.33 kB │ map:     0.79 kB
dist/assets/TheMap-228175f5.js        11.83 kB │ gzip:  4.54 kB │ map:    40.07 kB
dist/assets/TheCeramic-eb9494a8.js    75.45 kB │ gzip: 22.07 kB │ map:   221.88 kB
dist/assets/index-ac8c6ed2.js        197.67 kB │ gzip: 68.61 kB │ map: 1,387.24 kB
✓ built in 2.10s
```

**Review by francoiscrouzet — APPROVED** [review]
@chtzv It's all good for me, 
Since I opened a (long) discussion, I let you do the merge  just in case you want to do some change, but I don't see anything to change on my side

**Comment by AlZorba** [comment]
Sounds good to me too, same as @francoiscrouzet

**Comment by chtzv** [comment]
@francoiscrouzet, thanks for the test! I have no previous experience with
this but, from what I read, I understood the same as you: the components
will be split in chunks and load only on demand. I am surprised that
TheCeramic is much heavier than TheMap. Is it possible that it comprises
all the xrf results?

As for parallel loading - maybe this is relevant to components grouped
within the same chunk?

**Comment by francoiscrouzet** [comment]
> 

@chtzv ah you're right, I didn't see this difference. Yes, I think too it's becasue of the xrf
For parralel loading, I am not sure to understand what you mean. I think it's the opsosite, it's relevant when the browser need to load separate files. Let's see how it's behave once in production !!

**Comment by chtzv** [comment]
@francoiscrouzet, as I understand it, loading the entire xrf dataset is required every time a ceramic page is requested, correct? Still, I feel uneasy with bundling together code and data. Is this the best option in terms of performance?

**Comment by francoiscrouzet** [comment]
> @francoiscrouzet, as I understand it, loading the entire xrf dataset is required every time a ceramic page is requested, correct? Still, I feel uneasy with bundling together code and data. Is this the best option in terms of performance?

Hey @chtzv this whole code need to be refactored first : https://github.com/archaiodata/thacer/issues/85

But anyway I suspect that the code needs the full data in all case.
If not, yes it would be better to have an API sending back just the data we need. 
If yes, then we have static data that is 100% needed in the front, 

So in term of performance, I think it's the best
Otherwise, an api to get all the code would be less or  the same performance. 
And loading the file separatly is actually just what we do, and the production bundle put it in the js for performance I think

In term of clean code / best practice, I am ok with having this kind of "utility data" in the front code, as long as it is in the assets folder. Maybe it should be in a assets/data folder, it would be better than mixing it with the js code

And finally if you feel uneasy, wait to read that: https://github.com/archaiodata/thacer/discussions/61
It is very readable if you translate it with www.deepl.com
this is a major topic where we are not sure what to do !

What do you think about this xrf?
What do you think about geojson (better answer in #61 ?)

**Pull request merged**
