### PR TITLE
#100 Make the logo text responsive

### PR DESCRIPTION
**Pull request by chtzv**
#100 Fix header break in mobile view

**Description** :    
@francoiscrouzet, this solves the problem with the header you noted in https://github.com/archaiodata/thacer/pull/93#issuecomment-1502982520

### CODE REVIEW

**Comment by chtzv** [comment]
@AlZorba , OK. In this version the font size is fixed as before, and only the letter spacing varies depending on the screen width. It works on the smallest smartphones. What do you think?

**Review by AlZorba — COMMENTED** [review]
very nice
maybe add bootstrap class "d-none d-sm-block" on line 47

**Comment by chtzv** [comment]
@AlZorba, hide info on mobile? The button is not causing a problem at the moment. Please confirm that you want it out.

**Comment by francoiscrouzet** [comment]
> @AlZorba, hide info on mobile? The button is not causing a problem at the moment. Please confirm that you want it out.

Maybe a solution which could satisfy both of you would be to have the title big on big screen, small on small screen, and keeping the button in both cases

It's super cool that thacer is becoming responsive !
There is a ticket about that : https://github.com/archaiodata/thacer/issues/59

**Comment by AlZorba** [comment]
yes cool, Thacer is becoming mobile friendly

**Pull request merged**
